### PR TITLE
Fix build with OpenBMC 2.10.0-dev

### PR DESCRIPTION
**Pull request by nest1ing**
The build with OpenBMC 2.10.0-dev fails.
It uses GCC-10.2.0 and an error message looks like:
```
parser/fmtexcept.hpp: In instantiation of 'eSEL::InvalidFormat::InvalidFormat(const char*, A&& ...) [with A = {}]':
parser/event.cpp:107:51:   required from here
parser/fmtexcept.hpp:47:37: error: format not a string literal and no format arguments [-Werror=format-security]
  47 |             const int len = snprintf(nullptr, 0, fmt, std::forward<A>(args)...);
     |                             ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
parser/fmtexcept.hpp:53:25: error: format not a string literal and no format arguments [-Werror=format-security]
   53 |                 snprintf(msg_.data(), msg_.size(), fmt,
      |                 ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   54 |                          std::forward<A>(args)...);
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~
```

This brings an overloaded constructor with only one argument and fixes
the build.

Signed-off-by: Alexander Filippov <a.filippov@yadro.com>

### CODE REVIEW

**Review by artemsen — APPROVED** [review]

**Review by AlexanderAmelkin — APPROVED** [review]
Funny how the upstream code fails to build on 64-bit systems because of them using `"%llX"` instead of `"%" PRIX64`...
